language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.10"
env:
  - export COVERALLS_SERVICE_NAME=travis-ci
before_install: npm install -g grunt-cli
install: npm install
script: npm run-script test-on-travis
